# Generated by Django 3.2.5 on 2021-10-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image_type',
            field=models.CharField(choices=[('cover', 'cover'), ('event', 'event')], default='event', help_text='Type of Image', max_length=50),
        ),
    ]
