# Generated by Django 3.2.5 on 2021-10-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211010_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesupload',
            name='image_type',
            field=models.CharField(choices=[('cover', 'cover'), ('event', 'event')], default='event', help_text='Type of Image', max_length=50),
        ),
    ]
