# Generated by Django 3.2.5 on 2022-07-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_events_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_end_date',
            field=models.DateField(null=True),
        ),
    ]
