# Generated by Django 3.2.5 on 2022-08-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20220809_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
