# Generated by Django 3.0.7 on 2020-09-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_curateimages'),
        ('notifications', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
