# Generated by Django 3.0.7 on 2020-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_userscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='desirable_score',
            field=models.FloatField(default=0.0, help_text='Desirable Score based on Profile and Network'),
        ),
    ]
