# Generated by Django 3.0.7 on 2020-07-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20200713_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontacts',
            old_name='user',
            new_name='following',
        ),
    ]
