# Generated by Django 3.0.7 on 2020-07-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_userlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'ordering': ['-desirable_score']},
        ),
    ]
