# Generated by Django 3.0.7 on 2020-10-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_auto_20200825_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='place',
            field=models.TextField(blank=True, help_text='Name of Place of last location', null=True),
        ),
    ]
