# Generated by Django 2.2.13 on 2020-12-24 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0010_auto_20201016_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontacts',
            name='hosted_events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_hosted_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
