# Generated by Django 2.2.13 on 2020-12-30 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_usercontacts_hosted_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='hosted_events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_hosted_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
