# Generated by Django 3.0.7 on 2020-06-23 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0012_auto_20200623_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(help_text='Name of Events', max_length=240)),
                ('event_type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], help_text='Type of Events', max_length=10)),
                ('description', models.TextField(help_text='Description of Events')),
                ('location', models.CharField(help_text='Location of Events, Inclues City and Country Code', max_length=240)),
                ('event_date', models.DateField()),
                ('event_time_from', models.TimeField()),
                ('event_time_to', models.TimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('event_interest', models.ManyToManyField(related_name='event', to='userprofile.Interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
