# Generated by Django 3.0.7 on 2020-06-25 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_eventimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='interested_users',
            field=models.ManyToManyField(related_name='interested_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
