# Generated by Django 3.0.7 on 2020-07-20 09:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200702_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
