# Generated by Django 3.0.7 on 2020-07-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_remove_profiledetails_desirable_score'),
        ('events', '0005_events_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of Events', max_length=240)),
                ('description', models.TextField(help_text='Description of Events')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('categoery', models.ManyToManyField(related_name='categoery', to='userprofile.Interest')),
            ],
        ),
    ]
