# Generated by Django 3.0.7 on 2020-08-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_price',
            field=models.FloatField(default=0.0, help_text='Creator Can add Price of Events'),
        ),
    ]
