# Generated by Django 3.0.7 on 2020-08-06 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_events_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='invited_users',
            field=models.ManyToManyField(related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
