# Generated by Django 3.0.7 on 2020-08-06 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_events_invited_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='interested_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='invited_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
