# Generated by Django 3.0.7 on 2020-09-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200825_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurateImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='currated_images/')),
                ('curated_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currated_images', to='events.CuratedEvents')),
            ],
        ),
    ]
