# Generated by Django 3.0.7 on 2020-10-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_displaypicture'),
        ('events', '0012_curateimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_interest', to='userprofile.Interest'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
