# Generated by Django 3.0.7 on 2020-10-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20201009_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_address',
            field=models.TextField(blank=True, help_text='Event Address', null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Close Friends', 'Close Friends')], help_text='Type of Events', max_length=50),
        ),
    ]
