# Generated by Django 3.0.7 on 2020-10-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_displaypicture'),
        ('events', '0015_auto_20201013_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedevents',
            name='categoery',
            field=models.ManyToManyField(blank=True, null=True, related_name='categoery', to='userprofile.Interest'),
        ),
    ]
