# Generated by Django 3.0.7 on 2020-10-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20201013_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(upload_to='event_images/')),
            ],
        ),
        migrations.CreateModel(
            name='EventsImageURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='events.Events')),
            ],
        ),
    ]
