# Generated by Django 3.0.7 on 2020-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventsimageurl_imagesupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_price',
            field=models.FloatField(blank=True, default=0.0, help_text='Creator Can add Price of Events', null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
