# Generated by Django 3.0.7 on 2020-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20201028_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_price',
            field=models.FloatField(blank=True, help_text='Creator Can add Price of Events', null=True),
        ),
    ]
