# Generated by Django 3.0.7 on 2020-12-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20201124_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsImageURL',
        ),
    ]
