# Generated by Django 2.2.13 on 2021-01-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_delete_eventsimageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_city',
            field=models.CharField(blank=True, help_text='City of Events', max_length=100, null=True),
        ),
    ]
