# Generated by Django 3.0.7 on 2020-08-17 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_remove_profiledetails_desirable_score'),
        ('chatting', '0005_auto_20200727_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='userprofile.ProfileDetails'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='userprofile.ProfileDetails'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
