# Generated by Django 3.0.7 on 2020-06-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200616_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest_name', models.CharField(blank=True, help_text='Name of Interest', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='interest',
            field=models.ManyToManyField(to='userprofile.Interest'),
        ),
    ]
