# Generated by Django 3.0.7 on 2020-06-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200617_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest_name',
            field=models.CharField(blank=True, help_text='Name of Interest', max_length=50, unique=True),
        ),
    ]
