# Generated by Django 3.0.7 on 2020-06-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_userimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='images',
            field=models.ImageField(upload_to='user_images/'),
        ),
    ]
