# Generated by Django 3.0.7 on 2020-06-18 10:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0007_auto_20200618_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposite_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], help_text='User interested in Opposite Gender', max_length=6)),
                ('min_age', models.IntegerField(default=18, help_text='Minimum Age group user want to meet', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)])),
                ('max_age', models.IntegerField(default=18, help_text='Maximum Age group user want to meet', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)])),
                ('radius', models.FloatField(default=10.0, help_text='In maximum radius, user want to meet in KMs', validators=[django.core.validators.MaxValueValidator(161), django.core.validators.MinValueValidator(2)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
