# Generated by Django 3.0.7 on 2020-06-19 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0008_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(help_text='Instagram ID of User', max_length=50)),
                ('access_token', models.TextField(help_text='Long Lived Accesse token')),
                ('token_expiry', models.CharField(help_text='Last Date of Expiry', max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
