# Generated by Django 3.0.7 on 2020-06-22 03:52

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_instagramconnect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='dob',
            field=models.DateField(validators=[userprofile.models.date_validation]),
        ),
    ]
