# Generated by Django 3.0.7 on 2020-06-22 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20200622_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='max_age',
            field=models.IntegerField(default=19, help_text='Maximum Age group user want to meet', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(19)]),
        ),
    ]
