# Generated by Django 3.0.7 on 2020-07-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20200713_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='desirable_score',
            field=models.FloatField(default=0, help_text='Desirable Score based on Profile and Network'),
        ),
    ]
