# Generated by Django 3.0.7 on 2020-07-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_profiledetails_desirable_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='desirable_score',
            field=models.FloatField(default=500.0, help_text='Desirable Score based on Profile and Network'),
        ),
    ]
