# Generated by Django 3.0.7 on 2020-07-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20200713_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='desirable_score',
        ),
    ]
