# Generated by Django 3.0.7 on 2020-08-25 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0017_spotifyconnect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
