# Generated by Django 3.0.7 on 2020-08-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_auto_20200825_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='home_town',
            field=models.CharField(blank=True, help_text='Home Town', max_length=100),
        ),
    ]
