# Generated by Django 3.0.7 on 2020-09-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_profiledetails_home_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='interest', to='userprofile.Interest'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='opposite_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], help_text='User interested in Opposite Gender', max_length=6, null=True),
        ),
    ]
