# Generated by Django 3.0.7 on 2020-11-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_profiledetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='username',
            field=models.CharField(blank=True, help_text='Username associate with Profile', max_length=100, null=True, unique=True),
        ),
    ]
