# Generated by Django 3.0.7 on 2020-12-07 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0025_auto_20201104_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Sample Questions', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPromptQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, help_text='Answer to question', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_questions', to='userprofile.PromptQuestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prompt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
