# Generated by Django 3.0.7 on 2020-12-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_promptquestions_userpromptqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='recorvery_mail',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
