# Generated by Django 2.2.13 on 2020-12-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0027_profiledetails_recorvery_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='education',
            field=models.CharField(blank=True, help_text='Designation at Work Place', max_length=100),
        ),
    ]
