# Generated by Django 2.2.13 on 2020-12-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0028_profiledetails_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='company',
            field=models.CharField(blank=True, help_text='Company', max_length=100),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='education',
            field=models.CharField(blank=True, help_text='Education', max_length=100),
        ),
    ]
