# Generated by Django 2.2.13 on 2020-12-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0029_auto_20201229_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='education',
            field=models.CharField(blank=True, help_text='education', max_length=100),
        ),
    ]
