# Generated by Django 2.2.13 on 2021-01-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0030_auto_20201230_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender of User', max_length=10),
        ),
    ]
