# Generated by Django 2.2.13 on 2021-01-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0031_auto_20210115_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='city',
            field=models.CharField(blank=True, help_text='lives at', max_length=100),
        ),
    ]
