# Generated by Django 2.2.13 on 2021-01-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0032_profiledetails_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
