# Generated by Django 2.2.13 on 2021-01-29 11:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest_name', models.CharField(blank=True, help_text='Name of Interest', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Sample Questions', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPromptQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, help_text='Answer to question', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_questions', to='userprofile.PromptQuestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prompt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposite_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], help_text="User interested in Opposite Gender. **It is removed that why it's made optional", max_length=6, null=True)),
                ('min_age', models.IntegerField(default=18, help_text='Minimum Age group user want to meet', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)])),
                ('max_age', models.IntegerField(default=19, help_text='Maximum Age group user want to meet', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(19)])),
                ('radius', models.FloatField(default=10.0, help_text='In maximum radius, user want to meet in KMs', validators=[django.core.validators.MaxValueValidator(161), django.core.validators.MinValueValidator(2)])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='user_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(help_text='Refresh Token to Get New Access Token')),
                ('access_token', models.TextField(help_text='Use Access Token if generated before One hours')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Username associate with Profile', max_length=100, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender of User', max_length=10)),
                ('dob', models.DateField(validators=[userprofile.models.date_validation])),
                ('full_name', models.CharField(help_text='Full name of User', max_length=40)),
                ('home_town', models.CharField(blank=True, help_text='Home Town', max_length=100)),
                ('work_as', models.CharField(blank=True, help_text='Designation at Work Place', max_length=100)),
                ('company', models.CharField(blank=True, help_text='Company', max_length=100)),
                ('education', models.CharField(blank=True, help_text='education', max_length=100)),
                ('city', models.CharField(blank=True, help_text='lives at', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Description of User')),
                ('fun_fact', models.TextField(blank=True, help_text='Fun Fact of User')),
                ('enjoy', models.TextField(blank=True, help_text='Description of things user enjoy doing')),
                ('is_available', models.BooleanField(default=False)),
                ('recorvery_mail', models.TextField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('interest', models.ManyToManyField(blank=True, null=True, related_name='interest', to='userprofile.Interest')),
                ('uuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(help_text='Instagram ID of User', max_length=50)),
                ('access_token', models.TextField(help_text='Long Lived Accesse token')),
                ('token_expiry', models.CharField(help_text='Last Date of Expiry', max_length=40)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='display_pic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_pic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
