# Generated by Django 2.2.13 on 2021-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='spotify_connected',
            field=models.BooleanField(default=False),
        ),
    ]
