# Generated by Django 2.2.13 on 2021-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profiledetails_spotify_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
