# Generated by Django 2.2.13 on 2021-02-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210212_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
