# Generated by Django 2.2.13 on 2021-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20210212_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='phone',
            field=models.CharField(blank=True, help_text='True', max_length=12),
        ),
    ]
