# Generated by Django 2.2.13 on 2021-03-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_usercontactlist_userscontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscontacts',
            name='contact_number',
            field=models.CharField(blank=True, help_text='contact_number', max_length=25, null=True),
        ),
    ]
