# Generated by Django 2.2.13 on 2021-03-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20210316_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='phone',
            field=models.CharField(blank=True, help_text='True', max_length=15),
        ),
    ]
