# Generated by Django 3.2.5 on 2021-10-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20210317_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='interest_img',
            field=models.ImageField(default=1, upload_to='categories/'),
            preserve_default=False,
        ),
    ]
