# Generated by Django 3.2.5 on 2021-10-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_interest_interest_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='interest_img',
            new_name='images',
        ),
    ]
