# Generated by Django 3.2.5 on 2022-07-06 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_rename_interest_img_interest_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimages',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
