# Generated by Django 3.2.5 on 2022-08-19 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0012_auto_20220706_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='liked_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
