# Generated by Django 3.2.5 on 2022-08-23 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0013_userimages_liked_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImagesComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userimages_comment_user', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userimages_replies', to='userprofile.userimagescomment')),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userimages_comment', to='userprofile.userimages')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
