# Generated by Django 3.2.5 on 2022-08-25 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0014_userimagescomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimagescomment',
            name='reply',
        ),
        migrations.AddField(
            model_name='userimagescomment',
            name='liked_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
