# Generated by Django 3.2.5 on 2022-09-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20220825_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userimages',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
