# Generated by Django 3.2.5 on 2021-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
