# Generated by Django 3.2.5 on 2022-08-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='activity_sub_type',
            field=models.CharField(choices=[('event_interested', 'event_interested'), ('event_created', 'event_created'), ('event_comment', 'event_comment'), ('following', 'following'), ('message', 'message')], default='default', help_text='notification sub type', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='activity_type',
            field=models.CharField(choices=[('event', 'event'), ('user', 'user')], help_text='Notification Type', max_length=20),
        ),
    ]
