# Generated by Django 3.2.5 on 2022-08-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20220809_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity_sub_type',
            field=models.CharField(choices=[('event_interested', 'event_interested'), ('event_created', 'event_created'), ('event_comment', 'event_comment'), ('following', 'following'), ('message', 'message'), ('event_going', 'event_going'), ('event_yettodecide', 'event_yettodecide')], help_text='notification sub type', max_length=20),
        ),
    ]
