# Generated by Django 3.2.5 on 2022-08-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_userimages_liked_user'),
        ('notifications', '0004_alter_notification_activity_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userimages'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='activity_sub_type',
            field=models.CharField(choices=[('event_interested', 'event_interested'), ('event_created', 'event_created'), ('event_comment', 'event_comment'), ('following', 'following'), ('message', 'message'), ('event_going', 'event_going'), ('event_yettodecide', 'event_yettodecide'), ('userimage_liked', 'userimage_liked')], help_text='notification sub type', max_length=20),
        ),
    ]
