# Generated by Django 3.2.5 on 2022-08-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20220822_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity_sub_type',
            field=models.CharField(choices=[('event_interested', 'event_interested'), ('event_created', 'event_created'), ('event_comment', 'event_comment'), ('following', 'following'), ('message', 'message'), ('event_going', 'event_going'), ('event_yettodecide', 'event_yettodecide'), ('userimage_liked', 'userimage_liked'), ('userimage_comment', 'userimage_comment'), ('userimage_comment_liked', 'userimage_comment_liked')], help_text='notification sub type', max_length=25),
        ),
    ]
